### ISSUE TITLE
Adding a DATE_FORMAT function

### ISSUE THREAD

**Issue by johngriffin** [sidewinderlabs/xlwrap#5]
I've created a DATE_FORMAT() function and committed it to my fork of this repo, see:
https://github.com/johngriffin/xlwrap/commit/107e0701f5559102152df7906e1d95c8ac14

I'd appreciate it if someone could review this as I'm pretty sure it would be of some use to others.  It works by taking two arguments: DATE_FORMAT (arg0, arg1)

arg0: a date string that will be parsed by pojava in to a Date object.

arg1: a format string that will be used by SimpleDateFormat to format our date accordingly.

_Example Usage:_

DATE_FORMAT('10th February 2009', 'MM');  // returns '02'

I'm sure that my implementation could be improved, and I'm not really a Java programmer, so I'd invite all feedback.

**Comment by ktk** [comment]
Hi John,

Thanks for the work, unfortunately we don't use the tracker here for tickets. Instead Mark set up a Pivotaltracker @ https://www.pivotaltracker.com/projects/215617

Would be great if you could report there.

**Comment by johngriffin** [comment]
Thanks for the pointer, I'll add it to pivotal.
