### ISSUE TITLE
Lauching server from Windows

### ISSUE THREAD

**Issue by Christian-B** [sidewinderlabs/xlwrap#9]
Hi,
Has anyone been able to Launch the server in windows.

**Comment by ktk** [comment]
We do use it on windows yes, why?

**Comment by Christian-B** [comment]
On 03/06/2011 13:42, ktk wrote:

> We do use it on windows yes, why?
> 
> Do you have a bat version of the Luanch script?

## 

Christian Brenninkmeijer
Department of Computer Science
University of Manchester

**Comment by lyne1991** [comment]
Hi,
I get "bin" command not found, when i run bin/server from windows command line. What do I need to do to launch the server?

**Comment by Christian-B** [comment]
On 07/07/2011 16:11, lyne1991 wrote:

> Hi,
> I get "bin" command not found, when i run bin/server from windows command line. What do I need to do to launch the server?
> 
> Hi Lyne,
> If I knew the answer I would not have created the issue,
> The current stuff only works in Linex.

## 

Christian Brenninkmeijer
Department of Computer Science
University of Manchester

**Comment by lyne1991** [comment]
Ok. Thanks

**Comment by Christian-B** [comment]
No longer required
